module.exports = {
    enumData: {
        pricings:["Thường", "Đồng", "Bạc", "Vàng","Kim Cương"],
        postStatus: ["Còn trống", "Đang đàm phán", "Đang bàn giao"],
        propertyTypes:[   
            'Căn hộ chung cư',
            'Nhà mặt phố',
            'Nhà riêng',
            'Nhà phố thương mại',
            'Biệt thự',
            'Đất nền',
            'Bán đất',
            'Trang trại',
            'Khu nghỉ dưỡng',
            'Kho',
            'Nhà xưởng',
            'Khác',
        ],
        listingTypes:["Bán", "Cho thuê"],
        directions:[
            "Đống - Bắc",
            "Tây - Nam",
            "Đông - Nam",
            "Tây - Bắc",
            "Đông",
            "Tây",
            "Nam",
            "Bắc",
        ]
    },
    gias:[
        {
            tenGia:"Thường",
            hienThiNgay:false,
            chiTietCapDo: 0.1,
            uuTien: 1,
            diemCanCo: 0,
            diemCanLenCap: 200000,
            ngayHetHan: 1,
            gia:0,
            duongDanHinhAnh:"/svg/badge-stock/base.svg",
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            tenGia:"Đồng",
            hienThiNgay: false,
            chiTietCapDo: 0.2,
            uuTien: 2,
            diemCanCo: 200000,
            diemCanLenCap: 500000,
            ngayHetHan: 3,
            gia: 200000,
            duongDanHinhAnh:"/svg/badge-stock/bronze.svg",
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            tenGia:"Bạc",
            hienThiNgay: true,
            chiTietCapDo: 0.3,
            uuTien: 2,
            diemCanCo: 500000,
            diemCanLenCap: 1000000,
            ngayHetHan: 7,
            gia: 500000,
            duongDanHinhAnh:"/svg/badge-stock/silver.svg",
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            tenGia:"Vàng",
            hienThiNgay: true,
            chiTietCapDo: 0.4,
            uuTien: 4,
            diemCanCo: 1000000,
            diemCanLenCap: 2000000,
            ngayHetHan: 10,
            gia: 1000000,
            duongDanHinhAnh:"/svg/badge-stock/gold.svg",
            createdAt: new Date(),
            updatedAt: new Date(),
        },
        {
            tenGia:"Kim Cương",
            hienThiNgay: true,
            chiTietCapDo: 0.5,
            uuTien: 5,
            diemCanCo: 2000000,
            diemCanLenCap: -1,
            ngayHetHan: 1,
            gia: 2000000,
            duongDanHinhAnh:"/svg/badge-stock/diamond.svg",
            createdAt: new Date(),
            updatedAt: new Date(),
        },
    ]
}